name: Release to npm

on:
    workflow_dispatch:
        inputs:
            version:
                description: The version to bump (if you choose custom, please include it under custom version)
                required: true
                default: 'patch'
                type: choice
                options:
                    - 'patch'
                    - 'minor'
                    - 'major'
                    - 'custom'
            custom_version:
                description: The custom version to bump to (only for "custom" type)
                required: false
                type: string
                default: ''

permissions:
    id-token: write # Required for OIDC
    contents: write # Required to push updates

jobs:
    build_and_test:
        name: Build and test
        uses: ./.github/workflows/test.yml
        secrets: inherit

    bump_version:
        name: Bump version
        needs: [build_and_test]
        runs-on: ubuntu-latest
        outputs:
            new_version_commit_sha: ${{ steps.commit.outputs.commit_long_sha || github.sha }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6
                with:
                    token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
                    fetch-depth: 0

            -   name: Set up Node.js
                uses: actions/setup-node@v6
                with:
                    node-version: '24'
                    package-manager-cache: false
                    registry-url: 'https://registry.npmjs.org'

            -   name: Install pnpm and dependencies
                uses: apify/workflows/pnpm-install@main

            -   name: Run TypeScript build
                run: pnpm build

            -   name: Bump version to custom version
                if: ${{ github.event.inputs.version == 'custom' && github.event.inputs.custom_version != '' }}
                run: pnpm version --no-git-tag-version ${{ github.event.inputs.custom_version }}
                env:
                    GIT_USER: 'noreply@apify.com:${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}'
                    GH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

            -   name: Bump version to ${{ github.event.inputs.version }} version
                if: ${{ github.event.inputs.version != 'custom' }}
                run: pnpm version --no-git-tag-version ${{ github.event.inputs.version }}
                env:
                    GIT_USER: 'noreply@apify.com:${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}'
                    GH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

            -   name: Commit changes
                id: commit
                uses: EndBug/add-and-commit@v10
                with:
                    author_name: Apify Release Bot
                    author_email: noreply@apify.com
                    message: 'chore(release): Update package version [skip ci]'
                    pull: '--rebase --autostash'

            -   name: Publish to npm
                run: pnpm publish --no-git-checks --provenance
